DemoSendGrid/Controllers/CorreoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace DemoSendGrid.Controllers
{
    public class CorreoController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult EnviarCorreo()
        {
            return View();
        }
        // TODO 003. Creamos la accion en el controlador para enviar correos.
        [HttpPost]
        public ActionResult EnviarCorreo(String CorreoUsuario, String Destino, String Asunto, String Mensaje, String Dni, String Nombre)
        {
            try
            {
                Asunto = Nombre + " con " + Dni + " quiere saber.....";

                new EnviarCorreos().PostMails(Nombre, CorreoUsuario, Destino, Asunto, Mensaje);
                //CC} finally {

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            try
            {
                Asunto = "Copia de tu solicitud con fecha" + DateTime.Now.Hour + ":" + DateTime.Now.Minute + " No respondas a este mensaje";
                Destino = CorreoUsuario;
                CorreoUsuario = "connecting.us2018@gmail.com";
                Nombre = "ConnectingUs";


             new EnviarCorreos().PostMails(Nombre, CorreoUsuario, Destino, Asunto, Mensaje);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }



            return RedirectToAction("Index");
        }



    }
}

DemoSendGrid/Views/Correo/EnviarCorreo.cshtml
@using System.ComponentModel
@{


}

    @* TODO 004. En la Vista, capturamos los datos que necesita el controlador*@
        @using (Html.BeginForm("EnviarCorreo", "Correo", FormMethod.Post))
        {
            <br/>
            <div class="form-horizontal col-md-7">

                <div class="form-group">
                    @Html.Label("Departamento", htmlAttributes: new { @class = "badge", style = "background-color: darkorchid" })
                 
                    <div >
                        @Html.DropDownList("Destino", new SelectList(new List<Object>
                    {
                    new {value="lerner20037@gmail.com", text="Ventas"},
                    new {value="lerner20037@gmail.com", text="Facturacion"},
                     new {value="lerner20037@gmail.com", text="PostVenta"},
                      new {value="lerner20037@gmail.com", text="Logistica"},
                       new {value="lerner20037@gmail.com", text="Calidad"},

                    }, "value", "text"), new { @class = "form-control" })

                    </div>
                </div>

                <div class="form-group">

                    <label for="Dni" class="badge" style="background-color: darkorchid">DNI</label>

                    <div>

                        <input id="Dni" name="Dni" type="text" class="form-control" placeholder="Ej. 09047565X"/>


                    </div>
                </div>

                <div class="form-group">

                    <label for="Nombre" class="badge" style="background-color: darkorchid">Nombre Cliente: </label>

                    <div>

                        <input id="Nombre" name="Nombre" type="text" class="form-control" placeholder="Ej. Maria Ortega"/>


                    </div>
                </div>

                <div class="form-group">

                    <label for="CorreoUsuario" class="badge" style="background-color: darkorchid">Email: </label>

                    <div>

                        <input id="CorreoUsuario" name="CorreoUsuario" type="text" class="form-control" placeholder="Ej. hola@adios.es" />


                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("Mensaje", new { @class = "badge", style="background-color: darkorchid"})
                    <div>
                        @Html.TextArea("Mensaje", null, new { maxlength = 500, rows = "10",  @class = "form-control", placeholder="Explica detalladamente el motivo de tu consulta, recibirás una copia en tu correo electrónico" })
                    </div>
                </div>
                <br />
                <div class="form-group">
                    <div class=btn-toolbar>
                        <input type="submit" value="Enviar Correo" class="btn btn-info" />
                        <button type="button" class="btn btn-default">
                            @Html.ActionLink("Menu", "Index")
                        </button>
                    </div>
                </div>
            </div>
        }

DemoSendGrid/Views/Correo/Index.cshtml
@{
    ViewBag.Title = "Pantalla Principal";
}
<img src="~/Images/SendGrid.png"  width="150px" height="150px"/>
<div class="btn-toolbar">
    <button type="button" class="btn btn-info">
        @Html.ActionLink("Contacta con Nosotros", "EnviarCorreo")
    </button>
    <button class="btn btn-warning"> Ver Cesta</button>
    <button class="btn btn-default"> Ver Tiendas </button>

</div>

DemoSendGrid/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Demo SendGrid</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body style="background-color: gainsboro">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Uso de SendGrid", "Index", "Correo", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
        
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>